name: PR Reporter Daily

on:
  schedule:
    # Runs every weekday at 9:00 AM Sofia, Bulgaria time (EEST UTC+3)
    # 9:00 AM EEST = 6:00 AM UTC
    - cron: '0 6 * * 1-5'
  
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  run-pr-reporter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: |
        go mod download
        go mod verify
        
    - name: Build application
      run: go build -o pr-reporter .
      
    - name: Run PR Reporter
      env:
        GITHUB_TOKEN: ${{ vars.GITHUB_TOKEN }}
        GITHUB_OWNER: ${{ vars.GITHUB_OWNER }}
        GITHUB_REPO: ${{ vars.GITHUB_REPO }}
        JIRA_URL: ${{ vars.JIRA_URL }}
        JIRA_USERNAME: ${{ vars.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ vars.JIRA_API_TOKEN }}
        SLACK_TOKEN: ${{ vars.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        TEAM_GROUP: ${{ vars.TEAM_GROUP }}
        USER_MAPPING: ${{ vars.USER_MAPPING }}
        DEBUG: ${{ vars.DEBUG }}
      run: ./pr-reporter --run-now
      
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pr-reporter-logs
        path: |
          *.log
          /tmp/*.log
        retention-days: 7